### PR TITLE
fix: Brings back docker support

### PR DESCRIPTION
**Pull request by benalf**
#1 Issue reported that docker setup is broken. It was simply 1 missing line compared to https://github.com/freeciv/freeciv-web configuration.

Basic docker setup is now working, tested on native Ubuntu 18.04 and WSL Ubuntu 18.04. Base setup uses around 600MB of RAM.

image

image

image

### CODE REVIEW

**Comment by Lexxie9952** [comment]
Thank you Benalf? Do you see anything else you think should be fixed?

**Comment by benalf** [comment]
Hey! If you mean anything to be fixed with the docker config, I'm not exactly sure. We started up a longturn game and it's too early to tell, but there were issues.

The things I had/have problems with which might or might not be docker config related:

- Flag webps are not generated automatically. I think I used `./sync-with-flags.sh` manually and it partially fixed it (some flags errored and remain blank).
- Missing database migrations. Some tables used in the code do not exist in the database. So far I've encountered `google_ip_log` and `cheaters`, might have more.
- MySQL version shipped with the docker container is older than required. I think you used `JSON` data type for that same `google_ip_log` table and it's not yet supported in the shipped version.

So far that's it. This can be fixed somewhat easily. However, I don't want anything to diverge from the Vagrant setup and at this point I don't fully understand which software parts are installed via the install script on first boot and which parts should be part the initial container/vbox image.

If I get a moment, I will look into it, maybe it helps getting some extra contributors. So far this fork has been an amazing upgrade compared to the _official_ freeciv-web version, thank you for the amazing work! :)

**Comment by andreasrosdal** [comment]
Thanks @benalf - Your contributions of the things you suggested would be welcome!

**Comment by Lexxie9952** [comment]
Hi Alfred!  First I want to say thanks for fixing the Docker thing. I don't
know how that got broken before. ;) I'll respond to the different things
you've written.

1.Flag webp's. Somewhere in the process for converting the svg flags to png
to webp, it was making a lot of the flags "broken" or graphically
inaccurate. Maybe about 5% to 10% not rendering right.  So a long time ago
I prevented that script from running because it would overwrite the fixed
flags I had put in by hand. It's the kind of minor issue that comes up when
running a live server and trying to keep people happy, but can result in
this kind of problem to the "shipped version." If there is a stable way to
handle it, that's great. I have accurate png and webp files on our live
server so maybe we can skip this process of mis-converting svg files? I
don't know. But I would like for our fork to be solid and fix these little
issues.

2. re: database. FCW had problems with a malicious hacker cheater, and made
some more tables and logging to help defend against these things. A
developer helped us with some of this, I think he might have kept some of
these cheater tables semi-secret. Now he's gone and I don't know what to do
about it, if it has broken things to prevent a build?

It helps a lot to get extra contributors. Thanks for reporting these things!

Lexxie

**Comment by benalf** [comment]
Hey @Lexxie9952 , glad to help!

Went though the setup files yesterday, I'll take a stab at improving the docker dev environment after work and see how far I get but it looks like it's gonna be a bit of a chore.

I'm considering making a clean Docker image with all the required things without any install scripts so that users can just pull a pre-built image and dive right in.

1. What is your usual workflow when doing development for the project? Do you always have to rebuild everything Tomcat related and wait for the new _.war_ to be live to test the changes? Maybe it's worth looking into adding a front-end build system with live hot module replacement so that less time is spent waiting for a fresh build? Considering the large codebase and extra sync scripts, it's a bit of a longshot but I do have a few ideas.

2. Do you need the Freeciv binary to be compilable from the environment at any time? This changes all the required _-dev_ dependencies that should be left in the final image. Maybe it's worth shipping the image with a prebuilt Freeciv but also allow recompiling at any time. Whatever is more convenient.

3. Is the whole Java Servlet back-end left as legacy with nobody willing to touch it unless absolutely necessary? I've noticed all the more recent API endpoints and helper services are written in pure python. I guess _old_ Java devs are scarce these days.

Hope I don't come off as intrusive and annoying with me stirring up your kitchen. I only wish to help in whatever way I can.

**Comment by Lexxie9952** [comment]
Hi again.

1. Usual workflow. Yeah I rebuild everything in vagrant. On local.  On main
server don't rebuild often and it only takes seconds over there.  It could
be good some other system but I have no idea how to do it.

2. We compile and change binary periodically, for fixing bugs or doing new
features.

3. I think so. I touch it so little that I don't know about it and feel bad
about it, and just surrender to not knowing what it does or how it works.

In one of life's little paradoxes, only people who never wonder if they are
intrusive, are the ones who actually are. So no, you're not intrusive at
all, and we try to welcome and encourage and entice more development! So
thanks for considering doing more!

Lexxie

**Pull request merged**
