### PR TITLE
Update to Freeciv server freeciv/freeciv@0a491620

### PR DESCRIPTION
**Pull request by kvilhaugsvik**
I'm still not able to test fcw properly. It may be a good idea to pull this branch and test it manually before merging.

Ruleset format changes:

Actions that targeted building or production has had the production targeted split to a separate action. To keep the old rules you should copy each enabler that was split, change its name and change the action to the production targeted variant.
"Targeted Sabotage City" is now "Targeted Sabotage City" and "Sabotage City Production".
"Targeted Sabotage City Escape" is now "Targeted Sabotage City Escape" and "Sabotage City Production Escape".
"Surgical Strike Building" is now "Surgical Strike Production" and "Surgical Strike Building".

The "Road" action has been renamed "Build Road". Change all references to it in action enablers and requirements.

### CODE REVIEW

**Comment by andreasrosdal** [comment]
Thanks for this contribution. 

Why aren't you able to test FCW properly? It's important to test the changes.

**Comment by kvilhaugsvik** [comment]
> Why aren't you able to test FCW properly?

I'm still not able to build fcw.org-server. You know how long it took me to get regular Freeciv-web to build on my set up.

This is why it may be a good idea that someone able to test it does testing before it is merged.

git fetch https://github.com/kvilhaugsvik/fcw.org-server.git lexxie-update
git checkout FETCH_HEAD

and then build and test it as usual before going back to where they used to be with

git checkout WHERE_YOU_USED_TO_BE

**Comment by andreasrosdal** [comment]
Can you please try harder to make FCW work on your system. Untested pull requests are bound to fail eventually.

**Comment by andreasrosdal** [comment]
Please submit an update. The pull request needs to have been tested. There are merge conflicts.

**Pull request closed without merging**
